version: '3.4'

services:
  questiondb:
    container_name: questiondb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

  gameserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:WhoKnowsKnowsUrl=http://whoknowsknows.grpc" 
    ports:
      - "5274:5274"

  whoknowsknows.api:
    container_name: whoknowsknows.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://questiondb:27017"
    depends_on:
      - questiondb
    ports:
      - "5005:5005"

  whoknowsknows.grpc:
    container_name: whoknowsknows.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://questiondb:27017" 
    depends_on:
      - questiondb
    ports:
      - "5001:5001"


  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;UserId=sa;Password=MATF12345678rs2"  
    depends_on:
      - mssql
    ports:
      - "4000:80"
